services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marykay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapeando porta do PostgreSQL para o host local

volumes:
  pgdata: